services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./local/data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: api
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  pg_data:
